# This is the project specific Settings.yml file.
# Place mksearch specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2013-2015
  project: MK SEARCH
  version: 1.5.7
  release: 1.5.7
  latex_documents:
  - - Index
    - MK SEARCH
    - Hannes Bochmann, Michael Wagner, René Nitzsche
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    restdoc:
    - http://docs.typo3.org/typo3cms/extensions/restdoc/
    - null
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    t3cmsapi:
    - http://typo3.org/api/typo3cms/
    - null
  extensions:
  - sphinx.ext.intersphinx
  - t3sphinx.ext.t3extras
  - t3sphinx.ext.t3tablerows
  - t3sphinx.ext.targets
...
